### ISSUE TITLE
Mod won't work as intended or instructions are unclear

### ISSUE THREAD

**Issue by deccaur** [Scherso/WeatherChanger#4]
Downloading and moving ''Weather.Changer-1.1.jar' from v2.0 Pre-Release appears to just be a client named "Essential" with no weather changing ability. There is no visible option to toggle settings for this mod in settings and Mod ID in Forge. Also worth noting, in #installation-guide step 3. where it says "Install the latest Weather Changer version" the link directs to another mod entirely. I may be misunderstood but this entire thing is very confusing.

**Comment by Scherso** [comment]
Oh my bad for the wrong link, I'll fix that right away, It was just a template I used for my mods in Markdown.

**Comment by Scherso** [comment]
As for your other issue, I am using the Essential Library in my mod, it does unfortunately come with a GUI that you can toggle. And to open my mods options, there is no GUI button, you would run the command /weatherchanger

**Comment by deccaur** [comment]
> 

I swear I tried that the first time but it appears as if I was indeed mistaken. Works Perfectly now, thank you very much

**Comment by Scherso** [comment]
Also, if you would like to use a mod that removes Essential, I'll be updating my mod, Not So Essential soon, if you to be early to that jar file you can contact me on discord.
